name=BLACKBLOX
version=0.1.0
author=BLACKBLOX
maintainer=BLACKBLOX <info@blackblox.si>
sentence=BLACKBLOX SDK for modular embedded systems.
paragraph=Platform-independent SDK for BLACKBLOX modules.
category=Device Control
url=https://github.com/BLACKBLOX-DEV/blackblox-sdk
architectures=*
includes=BLACKBLOX.h